# List of PII classes to anonymize. Remove an entry to stop detecting/returning that class.
pii_to_anonymize:
  - ACCOUNT_NUMBER
  - ADDRESS
  - AGE
  - AMOUNT
  - BUILDING_NUMBER
  - CITY
  - COMPANY_NAME
  - CREDIT_CARD_NUMBER
  - COUNTRY
  - CURRENCY
  - DEVICE_ID
  - DOB
  - DRIVER_LICENSE
  - EMAIL
  - ETHNICITY
  - GENDER
  - HEALTH_CONDITION
  - HEALTH_INSURANCE_ID
  - IBAN
  - IP_ADDRESS
  - JOB_TITLE
  - LATITUDE
  - LONGITUDE
  - MAC_ADDRESS
  - NATIONAL_ID
  - PASSPORT_NUMBER
  - PASSWORD
  - PERSON
  - PHONE_NUMBER
  - POLITICAL_OPINION
  - POSTAL_CODE
  - PREFIX
  - RELIGION
  - SALARY
  - SEXUAL_ORIENTATION
  - STATE
  - STREET
  - TAX_ID
  - URL
  - USERNAME
