pii_to_anonymize:
  - ACCOUNT_NUMBER
  - ADDRESS
  - BUILDING_NUMBER
  - CITY
  - COUNTRY
  - COMPANY_NAME
  - CREDIT_CARD_NUMBER
  - EMAIL
  - IBAN
  - JOB_TITLE
  - PASSWORD
  - PERSON
  - PHONE_NUMBER
  - POSTAL_CODE
  - STATE
  - STREET
  - USERNAME

mcp_config:
  - get_customer_contract_c014
  - get_merger_review_excerpts
  - get_customer_revenue
  - get_management_accounts
  - get_hr_payroll
  - get_hr_aggregate
  - get_kyc_details
  - get_kyc_status
  - get_third_party_note
  - get_technical_appendix
  - num_tool_calls
  