pii_to_anonymize:
  - ACCOUNT_NUMBER
  - ADDRESS
  - BUILDING_NUMBER
  - CITY
  - COMPANY_NAME
  - CREDIT_CARD_NUMBER
  - EMAIL
  - IBAN
  - JOB_TITLE
  - PASSWORD
  - PERSON
  - PHONE_NUMBER
  - POSTAL_CODE
  - STATE
  - STREET
  - USERNAME